### ISSUE TITLE
Task generateBukkitPluginDescription fails

### ISSUE THREAD

**Issue by Juli0q** [Minecrell/plugin-yml#46]
When I try to build my project I receive the following error:
```
Execution failed for task 'Project:generateBukkitPluginDescription'.
> 'com.fasterxml.jackson.core.io.ContentReference com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createContentReference(java.lang.Object)'
```

<details>
  <summary>My build.gradle.kts contents</summary>

  
```kotlin
bukkit {
    main = "main"
    version = pluginVersion
}

paper {
    website = "content"
    version = pluginVersion
    description = "content"
    authors = listOf("content")
    main = "main"
    foliaSupported = false
    apiVersion = "1.20"
}
```
</details>

**Comment by stephan-gh** [comment]
Please run the Gradle build with `--stacktrace`

**Comment by Juli0q** [comment]
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':Project:generateBukkitPluginDescription'.
Caused by: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.io.ContentReference com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createContentReference(java.lang.Object)'
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createGenerator(YAMLFactory.java:489)
	at com.fasterxml.jackson.databind.ObjectMapper.createGenerator(ObjectMapper.java:1179)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3684)
	at net.minecrell.pluginyml.GeneratePluginDescription.generate(GeneratePluginDescription.kt:86)

```

**Comment by stephan-gh** [comment]
This sounds like you have some other Gradle plugin enabled that also uses jackson but bundles it in an incompatible or older version for some reason.

**Comment by Juli0q** [comment]
Thx, with your clue, I found the problem: [Dokka](https://github.com/Kotlin/dokka), after I removed it, the build process worked again.
